spring:

  datasource:
    url: jdbc:mysql://mysql:3306/huan-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: huan
    password: huan

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect